name: Android Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Java + Gradle
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk gradle

      - name: Generate Gradle Wrapper if Missing
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "Gradle wrapper missing. Generating..."
            gradle wrapper
          else
            echo "Gradle wrapper already exists."
          fi

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: idle-kingdom-apk
          path: app/build/outputs/apk/debug/*.apk
